language: java
os:
 - linux
before_install:
 - date -u
 - uname -a
 - env | sort
branches:
 only:
   - v10.0.0-SNAPSHOT
jdk:
  - oraclejdk7
  - openjdk7
notifications:
 email:
  - support@openam.org.ru
cache:
  directories:
  - $HOME/.m2
script:
  - mvn install
