language: java
os:
 - linux
before_install:
 - date -u
 - uname -a
 - env | sort
branches:
 only:
   - master
   - v10.0.0-SNAPSHOT
   - v13.0.0-SNAPSHOT
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk8
  - openjdk7
notifications:
 email:
  - support@openam.org.ru
script:
  - mvn -f openam/ install
  - mvn -f openam-agents/jee-agents install
